In [ ]:
# Task5 

In [ ]:
 # Matrix Creation

# Using NumPy, create a 5×5 matrix with values ranging from 1 to 25

# Diagonal Extraction

# Extract the diagonal elements from your generated matrix

# Calculation

# Calculate the sum of the extracted diagonal elements

In [2]:
import numpy as np
matrix = np.arange(1, 26).reshape(5, 5)
print("5x5 Matrix:\n", matrix)

5x5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [3]:
diagonal = np.diag(matrix)
print("\nDiagonal Elements:", diagonal)


Diagonal Elements: [ 1  7 13 19 25]


In [4]:
sum_diagonal = np.sum(diagonal)
print("\nSum of Diagonal Elements:", sum_diagonal)


Sum of Diagonal Elements: 65
